language: node_js

node_js:
  - node
  - 8
  - 6

before_install:
  - phantomjs --version

before_script:
  - npm install @pattern-lab/patternengine-node-mustache
  - npm install @pattern-lab/patternengine-node-underscore
  - npm install @pattern-lab/patternengine-node-handlebars
  - npm install patternengine-node-twig

branches:
  only:
    - master
    - dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a14f537f16b0756d9470
    on_success: always
    on_failure: always
    on_start: never
