language: node_js

before_install:
  - phantomjs --version

before_script:
  - npm run bootstrap

branches:
  only:
    - master
    - dev

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a14f537f16b0756d9470
    on_success: always
    on_failure: always
    on_start: never
